### PR TITLE
Create README_ZH.md

### PR DESCRIPTION
**Pull request by hufei365**
Add Simplified Chinese version README

### CODE REVIEW

**Comment by L-Blondy** [comment]
Nice to have, however I'll be updating the docs quite a lot in the next few days and I won't be able to maintain the chinese docs since I don't speak chinese.
Have you thought of any continuous intnegration solution for this?

**Comment by hufei365** [comment]
This is indeed a question, and I would like to answer it from the following points:

Firstly, I came across up-fetch by chance, and after reading through it, I believe it to be an exceptionally good JavaScript library. It addresses a problem that many developers encounter. Therefore, I am very happy to recommend it to other developers and am willing to take on the translation work to promote it in regions where Chinese is spoken.

Secondly, to ensure the usability of the documentation, I think we can specify the version of the documentation to clearly state whether the current code matches the current documentation. Based on my past experience, I've found that differences in details do not cause too much trouble for developers, but the availability of a local language version can significantly affect its promotion. For example, in China, Vue.js is used more than React, largely because the Chinese documentation is better.

So, what do you think about me taking on the responsibility for the Chinese documentation? I currently have the time to do this. On a side note, if for some reason I am no longer able to maintain the updates for the Chinese documentation, I would also like to find someone else to take over my role. This should not be too difficult in my country.

**Comment by L-Blondy** [comment]
>  For example, in China, Vue.js is used more than React, largely because the Chinese documentation is better.

Yep China has a huge pool of devs that might struggle with english docs

> Firstly, I came across up-fetch by chance, and after reading through it, I believe it to be an exceptionally good JavaScript library.

I'm glad that you like it, there are some improvements to bring here and there but I'm pretty happy with what we've got so far

> and am willing to take on the translation work to promote it in regions where Chinese is spoken.

That would be awesome!

I updated the docs with a **raw fetch vs upfetch** section.
Would you mind translating it before I merge ?

I found out many persons struggled to understand the _why_ of this library.

Thank you for your work, and feel free to reach out to me and give some feedback!

**Comment by hufei365** [comment]
> I updated the docs with a **raw fetch vs upfetch** section.
> Would you mind translating it before I merge ?

Okay, no problem

Is it still located in README or is it another separate file？

**Comment by L-Blondy** [comment]
It is in the README
https://github.com/L-Blondy/up-fetch?tab=readme-ov-file#raw-fetch-vs-upfetch

I also dropped support for **deno** with the `npm:` specifier since deno does not support optional peerDependencies.

I may add it on a later version if requested by the users

**Pull request merged**
